/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Kursach;

import java.awt.Color;

public class App {
    
    public static EnergyObject[] energyObjects;
    public static MainForm UI;

    
    public static class EnergyObject{
        
        public String name;
        public double power;
        public static String description;
        private String programmName;
        private String programmNameOnMap;
        public short frequency;
        public String type;
        
        EnergyObject(String name, double power, String programmName, String programmNameOnMap, String type){
            
            this.name = name;
            this.power = power;
            this.description = "<html><h2>"+this.name+"</h2><br>Установленная эл. мощность: "+this.power+" МВт</html>";
            this.programmName = programmName;
            this.frequency = 50;
            this.programmNameOnMap = programmNameOnMap;
            this.type = type;
        }
        
        public void changeFrequency(short value){
            this.frequency = value;
            UI.labelMap.get(this.programmName).setForeground(Color.RED);
            UI.labelMap.get(this.programmNameOnMap).setText("");
        }
        
    }
    
    private static void createEnergyObjects(){
        energyObjects = new EnergyObject[20];
        energyObjects[0] = new EnergyObject("Карламановская ГРЭС",1856.2,"karlamanGRES","karlamanGRES_MAP","gres");
        energyObjects[1] = new EnergyObject("Мечетлинская малая ГЭС",0.445,"mechetlinGES","mechetlinGES_MAP","ges");
        energyObjects[2] = new EnergyObject("Павловская ГЭС",166.4,"pavlovGES","pavlovGES_MAP","ges");
        energyObjects[3] = new EnergyObject("Приуфимская ТЭЦ",210,"priufimCHP","priufimCHP_MAP","gres");
        energyObjects[4] = new EnergyObject("Уфимская ТЭЦ-3",95,"ufimCHP_3","ufimCHP_3_MAP","gres");
        energyObjects[5] = new EnergyObject("ВЭС 'Тюпкильды'",1.65,"tupkilWPP","tupkilWPP_MAP","gres");
        energyObjects[6] = new EnergyObject("Затонская ТЭЦ",440,"zatonCHP","zatonCHP_MAP","gres");
        energyObjects[7] = new EnergyObject("Уфимская ТЭЦ-1",23,"ufimCHP_1","ufimCHP_1_MAP","gres");
        energyObjects[8] = new EnergyObject("Уфимская ТЭЦ-2",519,"ufimCHP_2","ufimCHP_2_MAP","gres");
        energyObjects[9] = new EnergyObject("Уфимская ТЭЦ-4",270,"ufimCHP_4","ufimCHP_4_MAP","gres");
        energyObjects[10] = new EnergyObject("Слакская малая ГЭС",0.1,"slakGES","slakGES_MAP","ges");
        energyObjects[11] = new EnergyObject("Ново-Стерлитамакская ТЭЦ",255,"newsterCHP","newsterCHP_MAP","gres");
        energyObjects[12] = new EnergyObject("Стерлитамакская ТЭЦ",320,"sterCHP","sterCHP_MAP","gres");
        energyObjects[13] = new EnergyObject("МикроГЭС 'Авзян'",0.075,"avzyanGES","avzyanGES_MAP","ges");
        energyObjects[14] = new EnergyObject("МикроГЭС 'Кага'",0.075,"kagaGES","kagaGES_MAP","ges");
        energyObjects[15] = new EnergyObject("МикроГЭС 'Узян'",0.05,"uzanGES","uzanGES_MAP","ges");
        energyObjects[16] = new EnergyObject("Салаватская ТЭЦ",180,"salavatCHP","salavatCHP_MAP","gres");
        energyObjects[17] = new EnergyObject("Зауральская ТЭЦ",17.444,"zauralCHP","zauralCHP_MAP","gres");
        energyObjects[18] = new EnergyObject("ГТЭС 'Сибай'",16,"sibayGCHP","sibayGCHP_MAP","gres");
        energyObjects[19] = new EnergyObject("Юмагузинская ГЭС",45,"umaguzGES","umaguzGES_MAP","ges");
    }

    public static void main(String[] args) {
        createEnergyObjects();
        UI = new MainForm(energyObjects);
        UI.setVisible(true);
    }
}
